#!/bin/bash

FIXTURES_DIR="${BATS_TEST_DIRNAME}/fixtures"
SOURCE_DIR="${BATS_TEST_DIRNAME}/../../.."
TASKS_DIR="${SOURCE_DIR}/tasks"
PROJECT_ROOT_DIR="${BATS_TEST_DIRNAME}/../../../../"
COMMON_DIR="${BATS_TEST_DIRNAME}/../../../../common/src/main/bash"

export FIXTURES_DIR SOURCE_DIR TASKS_DIR PROJECT_ROOT_DIR COMMON_DIR
