pipeline-gradle.sh(1)
=====================
:compat-mode!:

NAME
----
pipeline-gradle.sh - a shell script

SYNOPSIS
--------

Contains all Gradle related build functions


FUNCTIONS
---------

 build
 executeApiCompatibilityCheck
 outputFolder
 printTestResults
 retrieveAppName
 retrieveGroupId
 retrieveStubRunnerIds
 runE2eTests
 runSmokeTests
 testResultsAntPattern

DETAILS
-------

Script Body
~~~~~~~~~~~

Has 22 line(s). No functions are called (may attach to Zle or do hooks, etc.).

build
~~~~~

____
 # Gradle implementation of build. Sets version, passes build options and distribution management properties.
 # Uses [PIPELINE_VERSION], [PASSED_PIPELINE_VERSION] and [M2_SETTINGS...], [REPO_WITH_BINARIES...] related env vars
____

Has 7 line(s). Calls functions:

 build
 `-- printTestResults

Not called by script or any function, may be a hook or Zle widget, etc.

executeApiCompatibilityCheck
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

____
 # Gradle implementation of executing API compatibility check
____

Has 6 line(s). Calls functions:

 executeApiCompatibilityCheck
 `-- printTestResults

Not called by script or any function, may be a hook or Zle widget, etc.

outputFolder
~~~~~~~~~~~~

____
 # Gradle implementation of output folder
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function, may be a hook or Zle widget, etc.

printTestResults
~~~~~~~~~~~~~~~~

____
 # Prints test results. Used by Concourse.
____

Has 1 line(s). Doesn't call other functions.

Called by:

 build
 executeApiCompatibilityCheck
 runE2eTests
 runSmokeTests

retrieveAppName
~~~~~~~~~~~~~~~

____
 # Gradle implementation of app name retrieval
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function, may be a hook or Zle widget, etc.

retrieveGroupId
~~~~~~~~~~~~~~~

____
 # Gradle implementation of group id retrieval
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function, may be a hook or Zle widget, etc.

retrieveStubRunnerIds
~~~~~~~~~~~~~~~~~~~~~

____
 # Extracts the stub runner ids from the Gradle properties
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function, may be a hook or Zle widget, etc.

runE2eTests
~~~~~~~~~~~

____
 # Given [APPLICATION_URL] will run the tests via [e2e] task
____

Has 9 line(s). Calls functions:

 runE2eTests
 `-- printTestResults

Not called by script or any function, may be a hook or Zle widget, etc.

runSmokeTests
~~~~~~~~~~~~~

____
 # Given [APPLICATION_URL] and [STUBRUNNER_URL] will run the tests via [smoke] task
____

Has 10 line(s). Calls functions:

 runSmokeTests
 `-- printTestResults

Not called by script or any function, may be a hook or Zle widget, etc.

testResultsAntPattern
~~~~~~~~~~~~~~~~~~~~~

____
 # Gradle implementation of test results ant pattern
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function, may be a hook or Zle widget, etc.

