pipeline-npm.sh(1)
==================
:compat-mode!:

NAME
----
pipeline-npm.sh - a shell script

SYNOPSIS
--------

Contains all NPM related build functions


FUNCTIONS
---------

 build
 downloadAppBinary
 downloadNpmIfMissing
 executeApiCompatibilityCheck
 installNodeIfMissing
 outputFolder
 projectType
 retrieveAppName
 retrieveGroupId
 retrieveStubRunnerIds
 runE2eTests
 runSmokeTests
 testResultsAntPattern

DETAILS
-------

Script Body
~~~~~~~~~~~

Has 15 line(s). No functions are called (may set up e.g. a hook, a Zle widget bound to a key, etc.).

Uses feature(s): _export_

_Exports (environment):_ ARTIFACT_TYPE [big]*//* NODE_BIN [big]*//* NPM_BIN

build
~~~~~

____
 # npm implementation of the build function.
 # Requires [npm] and [node]. Installs those if possible
____

Has 3 line(s). Calls functions:

 build
 `-- downloadNpmIfMissing
     `-- installNodeIfMissing

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_Environment variables used:_ NPM_BIN

downloadAppBinary
~~~~~~~~~~~~~~~~~

____
 # Just downloads the npm libraries. We will use sources
____

Has 2 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_Environment variables used:_ NPM_BIN

downloadNpmIfMissing
~~~~~~~~~~~~~~~~~~~~

____
 # Downloads and installs node and npm if missing
____

Has 6 line(s). Calls functions:

 downloadNpmIfMissing
 `-- installNodeIfMissing

Called by:

 build
 executeApiCompatibilityCheck
 retrieveAppName
 retrieveGroupId
 retrieveStubRunnerIds
 runE2eTests
 runSmokeTests

_Environment variables used:_ NPM_BIN

executeApiCompatibilityCheck
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

____
 # npm implementation of the execute API compatibility check
____

Has 2 line(s). Calls functions:

 executeApiCompatibilityCheck
 `-- downloadNpmIfMissing
     `-- installNodeIfMissing

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_Environment variables used:_ NPM_BIN

installNodeIfMissing
~~~~~~~~~~~~~~~~~~~~

____
 # Installs node if missing
____

Has 7 line(s). Doesn't call other functions.

Uses feature(s): _export_

Called by:

 downloadNpmIfMissing

_List of exports (to environment):_ LANG

_Environment variables used:_ NODE_BIN

outputFolder
~~~~~~~~~~~~

____
 # npm implementation of the output folder
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

projectType
~~~~~~~~~~~

____
 # npm implementation of the project type
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

retrieveAppName
~~~~~~~~~~~~~~~

____
 # npm implementation of the retrieve app name
____

Has 6 line(s). Calls functions:

 retrieveAppName
 `-- downloadNpmIfMissing
     `-- installNodeIfMissing

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_Environment variables used:_ pipeline-dotnet.sh -> PROJECT_NAME [big]*//* NPM_BIN

retrieveGroupId
~~~~~~~~~~~~~~~

____
 # npm implementation of the retrieve group id
____

Has 2 line(s). Calls functions:

 retrieveGroupId
 `-- downloadNpmIfMissing
     `-- installNodeIfMissing

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_Environment variables used:_ NPM_BIN

retrieveStubRunnerIds
~~~~~~~~~~~~~~~~~~~~~

____
 # npm implementation of the retrieve stub runner ids
____

Has 2 line(s). Calls functions:

 retrieveStubRunnerIds
 `-- downloadNpmIfMissing
     `-- installNodeIfMissing

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_Environment variables used:_ NPM_BIN

runE2eTests
~~~~~~~~~~~

____
 # npm implementation of the e2e tests
____

Has 2 line(s). Calls functions:

 runE2eTests
 `-- downloadNpmIfMissing
     `-- installNodeIfMissing

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_Environment variables used:_ NPM_BIN

runSmokeTests
~~~~~~~~~~~~~

____
 # npm implementation of the run smoke tests
____

Has 2 line(s). Calls functions:

 runSmokeTests
 `-- downloadNpmIfMissing
     `-- installNodeIfMissing

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_Environment variables used:_ NPM_BIN

testResultsAntPattern
~~~~~~~~~~~~~~~~~~~~~

____
 # npm implementation of the test results ant pattern
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

