pipeline-npm.sh(1)
==================
:compat-mode!:

NAME
----
pipeline-npm.sh - a shell script

SYNOPSIS
--------

Installs node if missing # 

FUNCTIONS
---------

 build
 downloadAppBinary
 downloadNpmIfMissing
 executeApiCompatibilityCheck
 installNodeIfMissing
 outputFolder
 projectType
 retrieveAppName
 retrieveGroupId
 runE2eTests
 runSmokeTests
 testResultsAntPattern

DETAILS
-------

Script Body
~~~~~~~~~~~

Has 15 line(s). No functions are called (may attach to Zle or do hooks, etc.).

build
~~~~~

____
 # npm implementation of the build function.
 # Requires [npm] and [node]. Installs those if possible
____

Has 3 line(s). Calls functions:

 build
 `-- downloadNpmIfMissing
     `-- installNodeIfMissing

Not called by script or any function, may be a hook or Zle widget, etc.

downloadAppBinary
~~~~~~~~~~~~~~~~~

____
 # Just downloads the npm libraries. We will use sources
____

Has 2 line(s). Doesn't call other functions.

Not called by script or any function, may be a hook or Zle widget, etc.

downloadNpmIfMissing
~~~~~~~~~~~~~~~~~~~~

____
 # Downloads and installs node and npm if missing
____

Has 6 line(s). Calls functions:

 downloadNpmIfMissing
 `-- installNodeIfMissing

Called by:

 build
 executeApiCompatibilityCheck
 retrieveAppName
 retrieveGroupId
 runE2eTests
 runSmokeTests

executeApiCompatibilityCheck
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

____
 # npm implementation of the execute API compatibility check
____

Has 2 line(s). Calls functions:

 executeApiCompatibilityCheck
 `-- downloadNpmIfMissing
     `-- installNodeIfMissing

Not called by script or any function, may be a hook or Zle widget, etc.

installNodeIfMissing
~~~~~~~~~~~~~~~~~~~~

____
 # Installs node if missing
____

Has 7 line(s). Doesn't call other functions.

Uses feature(s): _export_

Called by:

 downloadNpmIfMissing

outputFolder
~~~~~~~~~~~~

____
 # npm implementation of the output folder
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function, may be a hook or Zle widget, etc.

projectType
~~~~~~~~~~~

____
 # npm implementation of the project type
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function, may be a hook or Zle widget, etc.

retrieveAppName
~~~~~~~~~~~~~~~

____
 # npm implementation of the retrieve app name
____

Has 6 line(s). Calls functions:

 retrieveAppName
 `-- downloadNpmIfMissing
     `-- installNodeIfMissing

Not called by script or any function, may be a hook or Zle widget, etc.

retrieveGroupId
~~~~~~~~~~~~~~~

____
 # npm implementation of the retrieve group id
____

Has 2 line(s). Calls functions:

 retrieveGroupId
 `-- downloadNpmIfMissing
     `-- installNodeIfMissing

Not called by script or any function, may be a hook or Zle widget, etc.

runE2eTests
~~~~~~~~~~~

____
 # npm implementation of the e2e tests
____

Has 2 line(s). Calls functions:

 runE2eTests
 `-- downloadNpmIfMissing
     `-- installNodeIfMissing

Not called by script or any function, may be a hook or Zle widget, etc.

runSmokeTests
~~~~~~~~~~~~~

____
 # npm implementation of the run smoke tests
____

Has 2 line(s). Calls functions:

 runSmokeTests
 `-- downloadNpmIfMissing
     `-- installNodeIfMissing

Not called by script or any function, may be a hook or Zle widget, etc.

testResultsAntPattern
~~~~~~~~~~~~~~~~~~~~~

____
 # npm implementation of the test results ant pattern
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function, may be a hook or Zle widget, etc.

