= Common scripts

The logic behind the deployment pipeline is written using Bash scripts.

== Scripts

[source,bash]
----
.
├── build_and_upload.sh
├── build_api_compatibility_check.sh
├── pipeline-cf.sh
├── pipeline.sh
├── prod_complete.sh
├── prod_deploy.sh
├── projectType
│   ├── pipeline-gradle.sh
│   ├── pipeline-jvm.sh
│   └── pipeline-maven.sh
├── stage_deploy.sh
├── stage_e2e.sh
├── test_deploy.sh
├── test_rollback_deploy.sh
├── test_rollback_smoke.sh
└── test_smoke.sh
----

Spring Cloud Pipelines is built on top of conventions. Here's how they look like:

There is one script called `pipeline.sh` that contains all required functions
necessary to be implemented by any other scripts.

=== Supported platforms

In terms of platforms we support the convention looks as follows: `pipeline-${plaform}.sh`,
for example `pipeline-cf.sh` for Cloud Foundry implementations.

=== Supported building tools

Currently we support only JVM based applications via `projectType/pipeline-jvm.sh` and
building tools like Gradle and Maven (via `projectType/pipeline-gradle.sh` and
`projectType/pipeline-maven.sh`).

=== Customizations

In order to add a new platform (e.g. `aaa` platform) it's enough to create a new file called
 `pipeline-aaa.sh` and implement all functions present in the `pipeline.sh` file. Also
 you'll need to pass the `PAAS_TYPE=aaa` env variable to the bash scripts so that
  files get properly sourced.