= Common scripts

The logic behind the deployment pipeline is written using Bash scripts.

== Scripts

[source,bash]
----
.
├── build_and_upload.sh
├── build_api_compatibility_check.sh
├── k8s (kubernetes related configuration)
│   ├── eureka.yml
│   ├── ...
│   └── stubrunner-service.yml
├── pipeline-cf.sh
├── pipeline.sh
├── prod_complete.sh
├── prod_deploy.sh
├── projectType
│   ├── pipeline-gradle.sh
│   ├── pipeline-jvm.sh
│   └── pipeline-maven.sh
├── stage_deploy.sh
├── stage_e2e.sh
├── test_deploy.sh
├── test_rollback_deploy.sh
├── test_rollback_smoke.sh
└── test_smoke.sh
----

Spring Cloud Pipelines is built on top of conventions. Here's how they look like:

There is one script called `pipeline.sh` that contains all required functions
necessary to be implemented by any other scripts.

=== Supported platforms

In terms of platforms we support the convention looks as follows: `pipeline-${plaform}.sh`,
for example `pipeline-cf.sh` for Cloud Foundry implementations.

=== Supported building tools

Currently we support only JVM based applications via `projectType/pipeline-jvm.sh` and
building tools like Gradle and Maven (via `projectType/pipeline-gradle.sh` and
`projectType/pipeline-maven.sh`).

=== Customizations

In order to add a new platform (e.g. `aaa` platform) it's enough to create a new file called
`pipeline-aaa.sh` and implement all functions present in the `pipeline.sh` file. Also
you'll need to pass the `PAAS_TYPE=aaa` env variable to the bash scripts so that
files get properly sourced.

==== Override specific project type pipeline functions

If you want to replace one of the common functions located in `projectType/pipeline-gradle` or
`projectType/pipeline-maven.sh`, you don't have to copy and paste all the code that leads to the
execution of that function. Spring Cloud Pipelines provides a way to hook in custom shell scripts
that can override those functions. Spring Cloud Pipelines will source custom scripts located in
`common/src/main/bash/custom` after all of its own scripts have been sourced. Or if you set the
`CUSTOM_SCRIPT_IDENTIFIER` environment variable, then it will look for them under
`common/src/main/bash/<replaced_with_custom_script_identifier>`
where `<replaced_with_custom_script_identifier>` is the value of the `CUSTOM_SCRIPT_IDENTIFIER`
environment variable.

Specifically for Concourse, you also need to name the script that will replace the function the same name
as the Concourse task but with underscores in replace of the dashes.

For example, to customize the build-and-upload task in the Concourse pipeline, all you would need
to do is provide a script called `build_and_upload.sh` in your `common/src/main/bash/custom/`
folder and Spring Cloud Pipelines will automatically source it in.
Then, you can override the build function in `common/src/main/bash/projectType/pipeline-${projectType}`
with your own without re-writing all the logic up to that point. Here is an
https://github.com/pivotalservices/pcf-apptx-pipelines/tree/spike-150749835/common/src/main/bash/apptx[example]
and a https://github.com/malston/github-webhook/blob/spike-150749835/ci/pipeline.yml[pipeline] that uses it.
