I ran out of resources. (Cloud Foundry)::
[jenkins-cf-resources]] When deploying the application to stage or prod, you can get an `Insufficient resources` exception. The way to
solve it is to kill some applications from the test and stage environments. To do so, run the following commands:
+
====
[source,bash]
----
cf target -o pcfdev-org -s pcfdev-test
cf stop github-webhook
cf stop github-eureka
cf stop stubrunner
----
====
+
You can also run `./tools/cf-helper.sh kill-all-apps` to remove all demo-related apps
deployed to PCF Dev.

Deploying to test or stage or prod fails with an error about finding space (Cloud Foundry)::
You receive an exception similar to the following:
+
====
[source,bash]
----
20:26:18 API endpoint:   https://api.local.pcfdev.io (API version: 2.58.0)
20:26:18 User:           user
20:26:18 Org:            pcfdev-org
20:26:18 Space:          No space targeted, use 'cf target -s SPACE'
20:26:18 FAILED
20:26:18 Error finding space pcfdev-test
20:26:18 Space pcfdev-test not found
----
====
+
It means that you forgot to <<jenkins_pcfdev,create the spaces>> in your PCF Dev installation.

The route is already in use (Cloud Foundry).::
If you play around with Jenkins and Concourse, you can end up with routes that are
already occupied, as identified by errors similar to the following:
+
====
[source,bash]
----
Using route github-webhook-test.local.pcfdev.io
Binding github-webhook-test.local.pcfdev.io to github-webhook...
FAILED
The route github-webhook-test.local.pcfdev.io is already in use.
----
====
+
To resolve the issue, delete the offending routes, by using commands similar to the following:
+
====
[source,bash]
----
yes | cf delete-route local.pcfdev.io -n github-webhook-test
yes | cf delete-route local.pcfdev.io -n github-eureka-test
yes | cf delete-route local.pcfdev.io -n stubrunner-test
yes | cf delete-route local.pcfdev.io -n github-webhook-stage
yes | cf delete-route local.pcfdev.io -n github-eureka-stage
yes | cf delete-route local.pcfdev.io -n github-webhook-prod
yes | cf delete-route local.pcfdev.io -n github-eureka-prod
----
====
+
You can also run the `./tools/cf-helper.sh delete-routes` script.

How can I run helper scripts against a real Cloud Foundry instance that I'm logged into?::
Assuming that you are already logged into the cluster, uyou can run the
helper script with the `REUSE_CF_LOGIN=true` env variable, as shown in the following example:
+
====
[source,bash]
----
REUSE_CF_LOGIN=true ./tools/cf-helper.sh setup-prod-infra
----
====
+
This script create the MySQL database and the RabbitMQ service and downloads and deploys Eureka
to the space and organization you are logged into.
