== Customizing the project

=== Overriding scripts

Since Spring Cloud Pipelines evolves, you would like to pull the changes to your
Spring Cloud Pipelines fork. In order not to have merge conflicts, the best approach
to extending the functionality is to use a separate script with customizations.

When we execute a script that represents a step (e.g. with name `build_and_upload.sh`),
after we source all the deployment and build specific scripts (e.g. `pipeline-cf.sh`
and `projectType/pipeline-jvm.sh` with `projectType/pipeline-gradle.sh`), we set
a hook that allows to customize the behaviour. If the script that we're executing
is `common/src/main/bash/build_and_upload.sh` then we will search for a script in
Spring Cloud Pipelines repository under `common/src/main/bash/custom/build_and_upload.sh`
and we will source that script just before executing any functions.

Example of such customization can be seen below:

.custom/build_and_upload.sh
```bash
#!/bin/bash

function build() {
    echo "I am executing a custom build function"
}

export -f build
```

when the function `build` will be called for our Gradle project, then instead of
calling Gradle build process, we will just echo the `I am executing a custom build function`
text.

=== Overriding pipelines

Currently the best way for extension of Concourse and Jenkins pipelines is to make
a copy of the Concourse pipeline `yaml`s and Jenkins seed / pipeline jobs.

=== Leaving what's necessary

If you want to pick only pieces (e.g. you're interested only in `Cloud Foundry` with
`Concourse` combination) it's enough to execute this command:

```bash
$ ./gradlew customize
```

You'll see a screen looking more or less like this:

```bash
:customize
  ___          _              ___ _             _   ___ _           _ _
 / __|_ __ _ _(_)_ _  __ _   / __| |___ _  _ __| | | _ (_)_ __  ___| (_)_ _  ___ ___
 \__ \ '_ \ '_| | ' \/ _` | | (__| / _ \ || / _` | |  _/ | '_ \/ -_) | | ' \/ -_|_-<
 |___/ .__/_| |_|_||_\__, |  \___|_\___/\_,_\__,_| |_| |_| .__/\___|_|_|_||_\___/__/
     |_|             |___/                               |_|



Follow the instructions presented in the console or terminate the process to quit (ctrl + c)


=== PAAS TYPE ===
Which PAAS type do you want to use? Options: [CF, K8S, BOTH]
<-------------> 0% EXECUTING
> :customize
```

Now you need to answer a couple of questions. That way whole files and its pieces
will get removed / updated accordingly. If you provide `CF` and `Concourse` options
thn `Kubernetes` and `Jenkins` configuration / folders / pieces of code in
the project will get removed.
