= Spring Cloud Pipelines

_Documentation Authors: Marcin Grzejszczak_

Spring, Spring Boot and Spring Cloud are tools that allow developers speed up the
time of creating new business features. It's common knowledge however that the
 feature is only valuable if it's in production. That's why companies
 spend a lot of time and resources on building their own deployment pipelines.

This project tries to solve the following problems:

- Creation of a common deployment pipeline
- Propagation of good testing & deployment practices
- Speed up the time required to deploy a feature to production

A common way of running, configuring and deploying applications lowers support costs
and time needed by new developers to blend in when they change projects.

== The opinionated pipeline

This repo contains an *opinionated pipeline* to deploy a Spring Cloud based microservice.
We've taken the following opinionated decisions:

- application built using Maven or Gradle wrappers
- application deployment to Cloud Foundry
- For Maven:
    * usage of Maven Wrapper
    * artifacts deployment by `./mvnw clean deploy`
    * `stubrunner.ids` property to retrieve list of collaborators for which stubs should be downloaded
    * `repo.with.binaries` - (Injected by the pipeline) will contain the URL to the repo containing binaries (e.g. Artifactory)
    * `distribution.management.release.id` - (Injected by the pipeline) ID of the distribution management. Corresponds to server id in `settings.xml`
    * `distribution.management.release.url` - (Injected by the pipeline) Will contain the URL to the repo containing binaries (e.g. Artifactory)
    * running API compatibility tests via the `apicompatibility` Maven profile
    * `latest.production.version` - (Injected by the pipeline) will contain the latest production version for the repo (retrieved from Git tags)
    * running smoke tests on a deployed app via the `smoke` Maven profile
    * running end to end tests on a deployed app via the `e2e` Maven profile
- For Gradle (in the `github-analytics` application check the `gradle/pipeline.gradle` file):
    * usage of Gradlew Wrapper
    * `deploy` task for artifacts deployment
    * `REPO_WITH_BINARIES` - (Injected by the pipeline) will contain the URL to the repo containing binaries (e.g. Artifactory)
    * `M2_SETTINGS_REPO_USERNAME` - (Injected by the pipeline) Username used to send the binary to the repo containing binaries (e.g. Artifactory)
    * `M2_SETTINGS_REPO_PASSWORD` - (Injected by the pipeline) Password used to send the binary to the repo containing binaries (e.g. Artifactory)
    * running API compatibility tests via the `apiCompatibility` task
    * `latestProductionVersion` - (Injected by the pipeline) property will contain the latest production version for the repo (retrieved from Git tags)
    * running smoke tests on a deployed app via the `smoke` task
    * running end to end tests on a deployed app via the `e2e` task
    * `groupId` task to retrieve group id
    * `artifactId` task to retrieve artifact id
    * `currentVersion` task to retrieve the current version
    * `stubIds` task to retrieve list of collaborators for which stubs should be downloaded

This is the initial approach that can be easily changed since all the core
deployment logic is done in a form of Bash scripts.

You can go through the setup of the demo environment for

- <<concourse, Concourse>>
- <<jenkins, Jenkins using Jenkins Job DSL plugin>>

Each of these setups are available under the folders `jenkins` and
`concourse` respectively.

=== CI Server worker prerequisites

Spring Cloud Pipelines uses Bash scripts extensively. Below you can find the list of software
that needs to be installed on a CI server worker for the build to pass

[source,bash]
----
 apt-get -y install \
    bash \
    git \
    tar \
    zip \
    curl \
    ruby \
    wget \
    unzip \
    python \
    jq
----

=== Pipeline descriptor

Each application can contain a file called `pipeline.yml` with the following structure:

[source,yaml]
----
lowercaseEnvironmentName1:
    services:
        - type: service1Type
          name: service1Name
          coordinates: value
        - type: service2Type
          name: service2Name
          key: value
lowercaseEnvironmentName2:
    services:
        - type: service3Type
          name: service3Name
          coordinates: value
        - type: service4Type
          name: service4Name
          key: value
----

For a given environment we declare a list of infrastructure services that we
want to have deployed. Services have

    - `type` (example: `eureka`, `mysql`, `rabbitmq`, `stubrunner`) - this value gets
    then applied to the `deployService` Bash function
    - `name` - name of the service to get deployed
    - `coordinates` - coordinate that allows you to fetch the binary of the service.
      Examples: It can be a maven coordinate `groupid:artifactid:version`,
       docker image `organization/nameOfImage`, etc.
    - arbitrary key value pairs - you can customize the services as you wish

The `stubrunner` type can also have the `useClasspath` flag turned on to `true`
or `false`.

Example:

[source,yaml]
----
test:
  services:
    - type: rabbitmq
      name: rabbitmq-github-webhook
    - type: mysql
      name: mysql-github-webhook
    - type: eureka
      name: eureka-github-webhook
      coordinates: com.example.eureka:github-eureka:0.0.1.M1
    - type: stubrunner
      name: stubrunner-github-webhook
      coordinates: com.example.eureka:github-analytics-stub-runner-boot-classpath-stubs:0.0.1.M1
      useClasspath: true
stage:
  services:
    - type: rabbitmq
      name: rabbitmq-github
    - type: mysql
      name: mysql-github
    - type: eureka
      name: github-eureka
      coordinates: com.example.eureka:github-eureka:0.0.1.M1
----

When the deployment to test or deployment to stage occurs, Spring Cloud Pipelines
will:

    - for `test` environment, delete existing services and redeploy the ones from the list
    - for `stage` environment, if the service is not available it will get deployed. Otherwise
    nothing will happen

include::INTRO.adoc[]

include::CONCOURSE.adoc[]

include::JENKINS.adoc[]

include::DEMO.adoc[]

include::TECH.adoc[]