== Building the project

=== Prerequisites

As prerequisites you need to have http://www.shellcheck.net/[shellcheck],
https://github.com/sstephenson/bats[bats], https://stedolan.github.io/jq/[jq]
 and https://rubyinstaller.org/downloads/[ruby] installed. If you're on a Linux
 machine then `bats` and `shellcheck` will be installed for you.

To install the required software on Linux just type the following commands

[source,bash]
----
$ sudo apt-get install -y ruby jq
----

If you're on a Mac then just execute these commands to install the missing software

[source,bash]
----
$ brew install jq
$ brew install ruby
$ brew install bats
$ brew install shellcheck
----

=== Bats submodules

To make `bats` work properly we needed to attach Git submodules. To have them
initialized either clone with appropriate command

[source,bash]
----
$ git clone --recursive https://github.com/spring-cloud/spring-cloud-pipelines.git
----

or if you have already cloned the project and are just pulling changes

[source,bash]
----
$ git submodule init
$ git submodule update
----

If you forget about this step, then Gradle will execute these steps for you.

=== Build and test

Once you have installed all the prerequisites you can execute

[source,bash]
----
$ ./gradlew clean build
----

to build and test the project.

=== Generate docs

To generate docs just run

[source,bash]
----
$ ./gradlew generateDocs
----

=== Making a release

It's enough to execute the `release` task that will automatically
change the versions, build the docs, upload them to Spring Cloud Static,
tag the repo and then revert the changed versions back to default.

[source,bash]
----
$ ./gradlew release -PnewVersion=1.0.0.RELEASE
----

== Customizing the project

If you want to pick only pieces (e.g. you're interested only in `Cloud Foundry` with
`Concourse` combination) it's enough to execute this command:

```bash
$ ./gradlew customize
```

You'll see a screen looking more or less like this:

```bash
:customize
  ___          _              ___ _             _   ___ _           _ _
 / __|_ __ _ _(_)_ _  __ _   / __| |___ _  _ __| | | _ (_)_ __  ___| (_)_ _  ___ ___
 \__ \ '_ \ '_| | ' \/ _` | | (__| / _ \ || / _` | |  _/ | '_ \/ -_) | | ' \/ -_|_-<
 |___/ .__/_| |_|_||_\__, |  \___|_\___/\_,_\__,_| |_| |_| .__/\___|_|_|_||_\___/__/
     |_|             |___/                               |_|



Follow the instructions presented in the console or terminate the process to quit (ctrl + c)


=== PAAS TYPE ===
Which PAAS type do you want to use? Options: [CF, K8S, BOTH]
<-------------> 0% EXECUTING
> :customize
```

Now you need to answer a couple of questions. That way whole files and its pieces
will get removed / updated accordingly. If you provide `CF` and `Concourse` options
thn `Kubernetes` and `Jenkins` configuration / folders / pieces of code in
the project will get removed.

== Releasing the project

=== Publishing A Docker Image

When doing a release you also need to push a Docker image to Dockerhub.
From the project root, run the following commands replacing `<version>` with the
version of the release.

[source,bash]
----
docker login
docker build -t springcloud/spring-cloud-pipeline-jenkins:<version> ./jenkins
docker push springcloud/spring-cloud-pipeline-jenkins:<version>
----
