== Building the project

=== Prerequisites

As prerequisites you need to have http://www.shellcheck.net/[shellcheck],
https://github.com/sstephenson/bats[bats], https://stedolan.github.io/jq/[jq]
 and https://rubyinstaller.org/downloads/[ruby] installed. If you're on a Linux
 machine then `bats` and `shellcheck` will be installed for you.

To install the required software on Linux just type the following commands

[source,bash]
----
$ sudo apt-get install -y ruby jq
----

If you're on a Mac then just execute these commands to install the missing software

[source,bash]
----
$ brew install jq
$ brew install ruby
$ brew install bats
$ brew install shellcheck
----

=== Bats submodules

To make `bats` work properly we needed to attach Git submodules. To have them
initialized either clone with appropriate command

[source,bash]
----
$ git clone --recursive https://github.com/spring-cloud/spring-cloud-pipelines.git
----

or if you have already cloned the project and are just pulling changes

[source,bash]
----
$ git submodule init
$ git submodule update
----

If you forget about this step, then Gradle will execute these steps for you.

=== Build and test

Once you have installed all the prerequisites you can execute

[source,bash]
----
$ ./gradlew clean build
----

to build and test the project.

=== Generate docs

To generate docs just run

[source,bash]
----
$ ./gradlew generateDocs
----

=== Distributions

Spring Cloud Pipelines has a lot of tests, including Git repositories. Those
and the documentation weigh a lot. That's why under the `dist` folder we
publish `zip` and `tar.gz` distributions of sources without tests and documentation.
Whenever we release a distribution we attach a `VERSION` file to it that contains
build and SCM information (e.g. build time, revision). To skip the distribution generation
just pass the `skipDist` property

[source,bash]
----
$ ./gradlew build -PskipDist
----


=== Making a release

It's enough to execute the `release` task that will automatically test the project,
build the distributions, change the versions, build the docs, upload them to Spring Cloud Static,
tag the repo and then revert the changed versions back to default.

[source,bash]
----
$ ./gradlew release -PnewVersion=1.0.0.RELEASE
----

== Releasing the project

=== Publishing A Docker Image

When doing a release you also need to push a Docker image to Dockerhub.
From the project root, run the following commands replacing `<version>` with the
version of the release.

[source,bash]
----
$ docker login
$ docker build -t springcloud/spring-cloud-pipeline-jenkins:<version> ./jenkins
$ docker push springcloud/spring-cloud-pipeline-jenkins:<version>
----
